---
image: backend
tag: tilt
replicas: 1

ingress:
  annotations:
      cert-manager.io/cluster-issuer: letsencrypt
  host: backend
  tls: true
  paths:
    - route: /

pdb:
  minAvailable: 50%

autoscaling: {}

deployment:
  containerPort: 8080
  livenessProbePath: /health
  readinessProbePath: /health

pullPolicy: Always

service: {}

config:
  configmaps:
    - name: main
      type: env
      data:
        DB_HOST: postgresql
        DB_USER: postgres
        DB_NAME: meetup
